// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace MalgreToutV2.Models
{
    [Table("DemoPickupPoint")]
    public partial class DemoPickupPoint
    {
        [Key]
        public int PickupPointId { get; set; }
        [Required]
        [StringLength(255)]
        public string Name { get; set; }
        [Required]
        [StringLength(255)]
        public string Address { get; set; }
        [Required]
        [StringLength(20)]
        public string PostalCode { get; set; }
        [Required]
        [StringLength(60)]
        public string Country { get; set; }
        [Required]
        [StringLength(20)]
        public string PhoneNumber { get; set; }
        public int? NoOfMagazine { get; set; }
        public TimeSpan? OpeningTime { get; set; }
        public TimeSpan? CloseningTime { get; set; }

        [InverseProperty(nameof(DemoContactPerson.PickupPoint))]
        public virtual DemoContactPerson ContactPerson { get; set; }
    }
}