// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace MagreToutV2.Models
{
    [Table("DemoMagazine")]
    public partial class DemoMagazine
    {
        [Key]
        public int VersionId { get; set; }
        [Required]
        [StringLength(255)]
        public string Version { get; set; }
        public int? AdId { get; set; }

        [ForeignKey(nameof(AdId))]
        [InverseProperty(nameof(DemoAd.DemoMagazines))]
        public virtual DemoAd Ad { get; set; }
    }
}