// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace MalgreToutV2.Models
{
    [Table("DemoMagAd")]
    public partial class DemoMagAd
    {
        [Key]
        public int MagAdId { get; set; }
        public int VersionId { get; set; }
        public int AdId { get; set; }

        [ForeignKey(nameof(AdId))]
        [InverseProperty(nameof(DemoAd.DemoMagAds))]
        public virtual DemoAd Ad { get; set; }
        [ForeignKey(nameof(VersionId))]
        [InverseProperty(nameof(DemoMagazine.DemoMagAds))]
        public virtual DemoMagazine Version { get; set; }
    }
}