// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace MalgreToutV2.Models
{
    [Table("DemoMagazine")]
    public partial class DemoMagazine
    {
        public DemoMagazine()
        {
            DemoAds = new HashSet<DemoAd>();
        }

        [Key]
        public int VersionId { get; set; }
        [Required]
        [StringLength(255)]
        public string Version { get; set; }

        [InverseProperty(nameof(DemoAd.Version))]
        public virtual ICollection<DemoAd> DemoAds { get; set; }
    }
}