// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace MalgreToutV2.Models
{
    [Table("DemoAd")]
    public partial class DemoAd
    {
        [Key]
        public int AdId { get; set; }
        [Required]
        [StringLength(255)]
        public string Company { get; set; }
        [Column(TypeName = "decimal(18, 0)")]
        public decimal? AdPrice { get; set; }
        public int VersionId { get; set; }

        [ForeignKey(nameof(VersionId))]
        [InverseProperty(nameof(DemoMagazine.DemoAds))]
        public virtual DemoMagazine Version { get; set; }
    }
}